### ISSUE TITLE
Error: Unable to resolve module `./App.css`

### ISSUE THREAD

**Issue by depuleio** [richardzcode/a-theme-react#1]
I am trying to add UI theme to my sign up page. For some reason react-native cannot find my css file. Any ideas?

<img width="369" alt="screen shot 2018-02-06 at 2 11 31 pm" src="https://user-images.githubusercontent.com/16300466/35882712-11dec372-0b53-11e8-9c9a-6da88a168abe.png">

Here is App.js:
<img width="518" alt="screen shot 2018-02-06 at 2 11 41 pm" src="https://user-images.githubusercontent.com/16300466/35882713-11f83bd6-0b53-11e8-98ab-89ea7dfe942e.png">
<img width="618" alt="screen shot 2018-02-06 at 2 11 59 pm" src="https://user-images.githubusercontent.com/16300466/35882714-12160c06-0b53-11e8-84c8-6d6d300245f1.png">

**Comment by richardzcode** [comment]
Hey @depuleio As far as I know React Native does not take CSS files. React for building web app, but React Native is for building mobile native apps. The theming there is similar to CSS but actually different.  Also because of that `a-theme-react` is not able to be used in React Native app directly.
